url: https://sanduni-p.github.io/IntroPython-pandas/
project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  sidebar: 
    title: "Introduction to Python"
    logo: vignettes/images/banner.jpg
    style: "docked"
    search: true
    contents:
      - href: index.html
        text: Home
      - section: "Workshop Materials"
        contents: 
          - vignettes/1_Introduction.qmd
          - vignettes/2_Intro_pandas.qmd
          - vignettes/3_Data_manipulation.qmd
  
format:
  html:
    theme: 
      - cerulean
      - utils/css/custom.scss
    toc: true
    toc-expand: 1
    toc-title: Contents
    embed-resources: true
    css: utils/css/custom.css
    smooth-scroll: true
    code-copy: hover
    df-print: kable
    
jupyter: python3    
execute:
  cache: false

